--CREATE USER TABLE

CREATE TABLE IF NOT EXISTS USER (
    USER_ID VARCHAR (225) NOT NULL,
    EMAIL VARCHAR (225) NOT NULL,
    FIRST_NAME VARCHAR (225) NOT NULL,
    LAST_NAME VARCHAR (225) NOT NULL,
    CART_ID VARCHAR (225) NOT NULL,
    PASSWORD VARCHAR (225) NOT NULL,
    USER_NAME VARCHAR (225) NOT NULL,
    CREATED_AT TIMESTAMP  DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (USER_ID)
);

CREATE UNIQUE INDEX USER_ID_INDEX ON USER (USER_ID)

